################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/caxpy.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/ccopy.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/cdotc.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/cdotu.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/cgbmv.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/cgemm.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/cgemv.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/cgerc.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/cgeru.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/chbmv.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/chemm.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/chemv.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/cher.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/cher2.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/cher2k.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/cherk.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/chpmv.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/chpr.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/chpr2.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/crotg.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/cscal.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/csrot.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/csscal.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/cswap.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/csymm.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/csyr2k.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/csyrk.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/ctbmv.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/ctbsv.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/ctpmv.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/ctpsv.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/ctrmm.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/ctrmv.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/ctrsm.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/ctrsv.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/dasum.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/daxpy.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/dcabs1.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/dcopy.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/ddot.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/dgbmv.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/dgemm.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/dgemv.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/dger.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/dnrm2.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/drot.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/drotg.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/drotm.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/drotmg.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/dsbmv.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/dscal.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/dsdot.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/dspmv.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/dspr.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/dspr2.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/dswap.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/dsymm.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/dsymv.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/dsyr.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/dsyr2.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/dsyr2k.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/dsyrk.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/dtbmv.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/dtbsv.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/dtpmv.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/dtpsv.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/dtrmm.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/dtrmv.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/dtrsm.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/dtrsv.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/dzasum.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/dznrm2.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/icamax.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/idamax.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/isamax.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/izamax.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/lsame.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/sasum.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/saxpy.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/scabs1.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/scasum.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/scnrm2.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/scopy.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/sdot.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/sdsdot.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/sgbmv.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/sgemm.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/sgemv.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/sger.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/snrm2.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/srot.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/srotg.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/srotm.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/srotmg.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/ssbmv.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/sscal.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/sspmv.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/sspr.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/sspr2.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/sswap.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/ssymm.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/ssymv.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/ssyr.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/ssyr2.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/ssyr2k.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/ssyrk.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/stbmv.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/stbsv.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/stpmv.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/stpsv.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/strmm.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/strmv.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/strsm.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/strsv.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/xerbla.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/xerbla_array.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/zaxpy.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/zcopy.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/zdotc.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/zdotu.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/zdrot.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/zdscal.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/zgbmv.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/zgemm.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/zgemv.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/zgerc.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/zgeru.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/zhbmv.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/zhemm.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/zhemv.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/zher.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/zher2.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/zher2k.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/zherk.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/zhpmv.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/zhpr.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/zhpr2.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/zrotg.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/zscal.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/zswap.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/zsymm.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/zsyr2k.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/zsyrk.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/ztbmv.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/ztbsv.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/ztpmv.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/ztpsv.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/ztrmm.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/ztrmv.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/ztrsm.c \
../ndk-modules/lapack/jni/clapack/BLAS/SRC/ztrsv.c 

OBJS += \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/caxpy.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ccopy.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/cdotc.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/cdotu.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/cgbmv.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/cgemm.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/cgemv.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/cgerc.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/cgeru.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/chbmv.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/chemm.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/chemv.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/cher.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/cher2.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/cher2k.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/cherk.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/chpmv.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/chpr.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/chpr2.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/crotg.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/cscal.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/csrot.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/csscal.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/cswap.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/csymm.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/csyr2k.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/csyrk.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ctbmv.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ctbsv.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ctpmv.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ctpsv.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ctrmm.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ctrmv.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ctrsm.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ctrsv.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dasum.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/daxpy.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dcabs1.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dcopy.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ddot.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dgbmv.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dgemm.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dgemv.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dger.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dnrm2.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/drot.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/drotg.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/drotm.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/drotmg.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dsbmv.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dscal.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dsdot.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dspmv.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dspr.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dspr2.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dswap.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dsymm.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dsymv.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dsyr.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dsyr2.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dsyr2k.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dsyrk.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dtbmv.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dtbsv.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dtpmv.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dtpsv.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dtrmm.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dtrmv.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dtrsm.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dtrsv.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dzasum.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dznrm2.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/icamax.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/idamax.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/isamax.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/izamax.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/lsame.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/sasum.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/saxpy.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/scabs1.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/scasum.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/scnrm2.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/scopy.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/sdot.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/sdsdot.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/sgbmv.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/sgemm.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/sgemv.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/sger.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/snrm2.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/srot.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/srotg.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/srotm.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/srotmg.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ssbmv.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/sscal.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/sspmv.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/sspr.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/sspr2.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/sswap.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ssymm.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ssymv.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ssyr.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ssyr2.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ssyr2k.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ssyrk.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/stbmv.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/stbsv.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/stpmv.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/stpsv.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/strmm.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/strmv.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/strsm.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/strsv.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/xerbla.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/xerbla_array.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zaxpy.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zcopy.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zdotc.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zdotu.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zdrot.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zdscal.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zgbmv.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zgemm.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zgemv.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zgerc.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zgeru.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zhbmv.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zhemm.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zhemv.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zher.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zher2.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zher2k.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zherk.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zhpmv.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zhpr.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zhpr2.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zrotg.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zscal.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zswap.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zsymm.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zsyr2k.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zsyrk.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ztbmv.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ztbsv.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ztpmv.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ztpsv.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ztrmm.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ztrmv.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ztrsm.o \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ztrsv.o 

C_DEPS += \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/caxpy.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ccopy.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/cdotc.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/cdotu.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/cgbmv.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/cgemm.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/cgemv.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/cgerc.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/cgeru.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/chbmv.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/chemm.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/chemv.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/cher.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/cher2.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/cher2k.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/cherk.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/chpmv.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/chpr.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/chpr2.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/crotg.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/cscal.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/csrot.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/csscal.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/cswap.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/csymm.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/csyr2k.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/csyrk.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ctbmv.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ctbsv.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ctpmv.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ctpsv.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ctrmm.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ctrmv.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ctrsm.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ctrsv.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dasum.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/daxpy.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dcabs1.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dcopy.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ddot.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dgbmv.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dgemm.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dgemv.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dger.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dnrm2.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/drot.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/drotg.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/drotm.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/drotmg.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dsbmv.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dscal.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dsdot.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dspmv.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dspr.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dspr2.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dswap.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dsymm.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dsymv.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dsyr.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dsyr2.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dsyr2k.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dsyrk.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dtbmv.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dtbsv.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dtpmv.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dtpsv.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dtrmm.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dtrmv.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dtrsm.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dtrsv.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dzasum.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/dznrm2.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/icamax.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/idamax.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/isamax.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/izamax.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/lsame.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/sasum.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/saxpy.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/scabs1.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/scasum.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/scnrm2.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/scopy.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/sdot.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/sdsdot.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/sgbmv.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/sgemm.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/sgemv.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/sger.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/snrm2.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/srot.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/srotg.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/srotm.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/srotmg.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ssbmv.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/sscal.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/sspmv.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/sspr.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/sspr2.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/sswap.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ssymm.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ssymv.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ssyr.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ssyr2.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ssyr2k.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ssyrk.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/stbmv.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/stbsv.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/stpmv.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/stpsv.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/strmm.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/strmv.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/strsm.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/strsv.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/xerbla.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/xerbla_array.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zaxpy.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zcopy.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zdotc.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zdotu.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zdrot.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zdscal.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zgbmv.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zgemm.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zgemv.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zgerc.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zgeru.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zhbmv.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zhemm.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zhemv.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zher.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zher2.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zher2k.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zherk.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zhpmv.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zhpr.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zhpr2.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zrotg.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zscal.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zswap.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zsymm.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zsyr2k.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/zsyrk.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ztbmv.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ztbsv.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ztpmv.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ztpsv.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ztrmm.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ztrmv.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ztrsm.d \
./ndk-modules/lapack/jni/clapack/BLAS/SRC/ztrsv.d 


# Each subdirectory must supply rules for building sources it contributes
ndk-modules/lapack/jni/clapack/BLAS/SRC/%.o: ../ndk-modules/lapack/jni/clapack/BLAS/SRC/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -O2 -g -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


