################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/abort_.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/arithchk.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/backspac.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/c_abs.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/c_cos.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/c_div.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/c_exp.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/c_log.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/c_sin.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/c_sqrt.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/cabs.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/close.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/ctype.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_abs.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_acos.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_asin.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_atan.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_atn2.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_cnjg.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_cos.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_cosh.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_dim.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_exp.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_imag.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_int.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_lg10.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_log.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_mod.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_nint.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_prod.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_sign.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_sin.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_sinh.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_sqrt.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_tan.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_tanh.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/derf_.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/derfc_.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/dfe.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/dolio.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/dtime_.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/due.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/ef1asc_.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/ef1cmc_.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/endfile.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/erf_.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/erfc_.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/err.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/etime_.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/exit_.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/f77_aloc.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/f77vers.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/fmt.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/fmtlib.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/ftell64_.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/ftell_.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/getarg_.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/getenv_.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/h_abs.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/h_dim.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/h_dnnt.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/h_indx.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/h_len.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/h_mod.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/h_nint.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/h_sign.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/hl_ge.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/hl_gt.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/hl_le.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/hl_lt.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/i77vers.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/i_abs.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/i_dim.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/i_dnnt.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/i_indx.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/i_len.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/i_mod.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/i_nint.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/i_sign.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/iargc_.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/iio.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/ilnw.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/inquire.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/l_ge.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/l_gt.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/l_le.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/l_lt.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/lbitbits.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/lbitshft.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/lread.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/lwrite.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/main.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/open.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/pow_ci.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/pow_dd.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/pow_di.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/pow_hh.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/pow_ii.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/pow_qq.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/pow_ri.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/pow_zi.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/pow_zz.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/qbitbits.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/qbitshft.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_abs.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_acos.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_asin.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_atan.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_atn2.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_cnjg.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_cos.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_cosh.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_dim.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_exp.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_imag.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_int.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_lg10.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_log.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_mod.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_nint.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_sign.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_sin.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_sinh.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_sqrt.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_tan.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_tanh.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/rdfmt.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/rewind.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/rsfe.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/rsli.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/rsne.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/s_cat.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/s_cmp.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/s_copy.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/s_paus.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/s_rnge.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/s_stop.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/sfe.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/sig_die.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/signal_.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/signbit.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/sue.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/system_.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/typesize.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/uio.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/uninit.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/util.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/wref.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/wrtfmt.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/wsfe.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/wsle.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/wsne.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/xwsne.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/z_abs.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/z_cos.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/z_div.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/z_exp.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/z_log.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/z_sin.c \
../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/z_sqrt.c 

OBJS += \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/abort_.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/arithchk.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/backspac.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/c_abs.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/c_cos.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/c_div.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/c_exp.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/c_log.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/c_sin.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/c_sqrt.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/cabs.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/close.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/ctype.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_abs.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_acos.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_asin.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_atan.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_atn2.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_cnjg.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_cos.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_cosh.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_dim.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_exp.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_imag.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_int.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_lg10.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_log.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_mod.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_nint.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_prod.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_sign.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_sin.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_sinh.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_sqrt.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_tan.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_tanh.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/derf_.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/derfc_.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/dfe.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/dolio.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/dtime_.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/due.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/ef1asc_.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/ef1cmc_.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/endfile.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/erf_.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/erfc_.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/err.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/etime_.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/exit_.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/f77_aloc.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/f77vers.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/fmt.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/fmtlib.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/ftell64_.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/ftell_.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/getarg_.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/getenv_.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/h_abs.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/h_dim.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/h_dnnt.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/h_indx.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/h_len.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/h_mod.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/h_nint.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/h_sign.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/hl_ge.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/hl_gt.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/hl_le.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/hl_lt.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/i77vers.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/i_abs.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/i_dim.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/i_dnnt.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/i_indx.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/i_len.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/i_mod.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/i_nint.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/i_sign.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/iargc_.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/iio.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/ilnw.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/inquire.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/l_ge.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/l_gt.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/l_le.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/l_lt.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/lbitbits.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/lbitshft.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/lread.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/lwrite.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/main.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/open.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/pow_ci.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/pow_dd.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/pow_di.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/pow_hh.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/pow_ii.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/pow_qq.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/pow_ri.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/pow_zi.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/pow_zz.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/qbitbits.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/qbitshft.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_abs.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_acos.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_asin.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_atan.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_atn2.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_cnjg.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_cos.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_cosh.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_dim.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_exp.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_imag.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_int.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_lg10.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_log.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_mod.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_nint.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_sign.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_sin.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_sinh.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_sqrt.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_tan.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_tanh.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/rdfmt.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/rewind.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/rsfe.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/rsli.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/rsne.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/s_cat.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/s_cmp.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/s_copy.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/s_paus.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/s_rnge.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/s_stop.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/sfe.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/sig_die.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/signal_.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/signbit.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/sue.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/system_.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/typesize.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/uio.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/uninit.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/util.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/wref.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/wrtfmt.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/wsfe.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/wsle.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/wsne.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/xwsne.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/z_abs.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/z_cos.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/z_div.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/z_exp.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/z_log.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/z_sin.o \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/z_sqrt.o 

C_DEPS += \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/abort_.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/arithchk.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/backspac.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/c_abs.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/c_cos.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/c_div.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/c_exp.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/c_log.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/c_sin.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/c_sqrt.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/cabs.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/close.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/ctype.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_abs.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_acos.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_asin.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_atan.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_atn2.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_cnjg.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_cos.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_cosh.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_dim.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_exp.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_imag.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_int.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_lg10.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_log.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_mod.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_nint.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_prod.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_sign.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_sin.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_sinh.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_sqrt.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_tan.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/d_tanh.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/derf_.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/derfc_.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/dfe.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/dolio.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/dtime_.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/due.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/ef1asc_.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/ef1cmc_.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/endfile.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/erf_.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/erfc_.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/err.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/etime_.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/exit_.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/f77_aloc.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/f77vers.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/fmt.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/fmtlib.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/ftell64_.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/ftell_.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/getarg_.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/getenv_.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/h_abs.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/h_dim.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/h_dnnt.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/h_indx.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/h_len.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/h_mod.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/h_nint.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/h_sign.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/hl_ge.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/hl_gt.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/hl_le.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/hl_lt.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/i77vers.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/i_abs.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/i_dim.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/i_dnnt.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/i_indx.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/i_len.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/i_mod.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/i_nint.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/i_sign.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/iargc_.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/iio.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/ilnw.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/inquire.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/l_ge.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/l_gt.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/l_le.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/l_lt.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/lbitbits.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/lbitshft.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/lread.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/lwrite.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/main.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/open.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/pow_ci.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/pow_dd.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/pow_di.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/pow_hh.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/pow_ii.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/pow_qq.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/pow_ri.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/pow_zi.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/pow_zz.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/qbitbits.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/qbitshft.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_abs.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_acos.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_asin.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_atan.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_atn2.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_cnjg.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_cos.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_cosh.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_dim.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_exp.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_imag.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_int.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_lg10.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_log.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_mod.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_nint.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_sign.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_sin.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_sinh.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_sqrt.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_tan.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/r_tanh.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/rdfmt.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/rewind.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/rsfe.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/rsli.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/rsne.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/s_cat.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/s_cmp.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/s_copy.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/s_paus.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/s_rnge.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/s_stop.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/sfe.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/sig_die.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/signal_.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/signbit.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/sue.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/system_.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/typesize.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/uio.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/uninit.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/util.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/wref.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/wrtfmt.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/wsfe.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/wsle.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/wsne.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/xwsne.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/z_abs.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/z_cos.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/z_div.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/z_exp.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/z_log.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/z_sin.d \
./ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/z_sqrt.d 


# Each subdirectory must supply rules for building sources it contributes
ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/%.o: ../ndk-modules/lapack/jni/clapack/F2CLIBS/libf2c/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -O2 -g -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


