################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/alahdg.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/alareq.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/alarqg.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/alasmg.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/alasum.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/alasvm.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cbdt01.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cbdt02.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cbdt03.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cchkbb.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cchkbd.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cchkbk.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cchkbl.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cchkec.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cchkee.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cchkgg.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cchkgk.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cchkgl.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cchkhb.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cchkhs.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cchkst.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cckglm.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cckgqr.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cckgsv.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/ccklse.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cdrges.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cdrgev.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cdrgsx.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cdrgvx.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cdrvbd.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cdrves.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cdrvev.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cdrvgg.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cdrvsg.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cdrvst.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cdrvsx.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cdrvvx.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cerrbd.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cerrec.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cerred.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cerrgg.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cerrhs.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cerrst.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cget02.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cget10.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cget22.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cget23.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cget24.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cget35.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cget36.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cget37.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cget38.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cget51.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cget52.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cget54.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cglmts.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cgqrts.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cgrqts.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cgsvts.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/chbt21.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/chet21.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/chet22.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/chkxer.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/chpt21.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/chst01.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/clarfy.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/clarhs.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/clatm4.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/clctes.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/clctsx.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/clsets.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/csbmv.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/csgt01.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cslect.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cstt21.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cstt22.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cunt01.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/cunt03.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dbdt01.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dbdt02.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dbdt03.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dchkbb.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dchkbd.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dchkbk.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dchkbl.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dchkec.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dchkee.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dchkgg.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dchkgk.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dchkgl.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dchkhs.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dchksb.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dchkst.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dckglm.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dckgqr.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dckgsv.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dcklse.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/ddrges.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/ddrgev.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/ddrgsx.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/ddrgvx.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/ddrvbd.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/ddrves.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/ddrvev.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/ddrvgg.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/ddrvsg.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/ddrvst.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/ddrvsx.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/ddrvvx.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/derrbd.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/derrec.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/derred.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/derrgg.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/derrhs.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/derrst.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dget02.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dget10.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dget22.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dget23.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dget24.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dget31.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dget32.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dget33.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dget34.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dget35.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dget36.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dget37.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dget38.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dget39.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dget51.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dget52.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dget53.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dget54.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dglmts.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dgqrts.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dgrqts.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dgsvts.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dhst01.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dlafts.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dlahd2.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dlarfy.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dlarhs.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dlasum.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dlatb9.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dlatm4.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dlctes.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dlctsx.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dlsets.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dort01.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dort03.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dsbt21.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dsgt01.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dslect.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dspt21.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dstech.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dstect.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dstt21.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dstt22.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dsvdch.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dsvdct.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dsxt1.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dsyt21.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/dsyt22.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/ilaenv.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sbdt01.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sbdt02.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sbdt03.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/schkbb.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/schkbd.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/schkbk.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/schkbl.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/schkec.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/schkee.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/schkgg.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/schkgk.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/schkgl.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/schkhs.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/schksb.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/schkst.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sckglm.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sckgqr.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sckgsv.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/scklse.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sdrges.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sdrgev.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sdrgsx.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sdrgvx.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sdrvbd.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sdrves.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sdrvev.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sdrvgg.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sdrvsg.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sdrvst.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sdrvsx.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sdrvvx.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/serrbd.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/serrec.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/serred.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/serrgg.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/serrhs.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/serrst.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sget02.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sget10.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sget22.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sget23.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sget24.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sget31.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sget32.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sget33.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sget34.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sget35.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sget36.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sget37.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sget38.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sget39.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sget51.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sget52.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sget53.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sget54.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sglmts.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sgqrts.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sgrqts.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sgsvts.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/shst01.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/slafts.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/slahd2.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/slarfy.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/slarhs.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/slasum.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/slatb9.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/slatm4.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/slctes.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/slctsx.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/slsets.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sort01.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sort03.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/ssbt21.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/ssgt01.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sslect.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sspt21.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sstech.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sstect.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sstt21.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/sstt22.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/ssvdch.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/ssvdct.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/ssxt1.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/ssyt21.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/ssyt22.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/xerbla.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/xlaenv.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zbdt01.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zbdt02.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zbdt03.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zchkbb.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zchkbd.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zchkbk.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zchkbl.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zchkec.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zchkee.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zchkgg.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zchkgk.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zchkgl.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zchkhb.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zchkhs.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zchkst.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zckglm.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zckgqr.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zckgsv.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zcklse.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zdrges.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zdrgev.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zdrgsx.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zdrgvx.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zdrvbd.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zdrves.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zdrvev.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zdrvgg.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zdrvsg.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zdrvst.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zdrvsx.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zdrvvx.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zerrbd.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zerrec.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zerred.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zerrgg.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zerrhs.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zerrst.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zget02.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zget10.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zget22.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zget23.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zget24.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zget35.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zget36.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zget37.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zget38.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zget51.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zget52.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zget54.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zglmts.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zgqrts.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zgrqts.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zgsvts.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zhbt21.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zhet21.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zhet22.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zhpt21.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zhst01.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zlarfy.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zlarhs.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zlatm4.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zlctes.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zlctsx.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zlsets.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zsbmv.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zsgt01.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zslect.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zstt21.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zstt22.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zunt01.c \
../ndk-modules/lapack/jni/clapack/TESTING/EIG/zunt03.c 

OBJS += \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/alahdg.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/alareq.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/alarqg.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/alasmg.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/alasum.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/alasvm.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cbdt01.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cbdt02.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cbdt03.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cchkbb.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cchkbd.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cchkbk.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cchkbl.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cchkec.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cchkee.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cchkgg.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cchkgk.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cchkgl.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cchkhb.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cchkhs.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cchkst.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cckglm.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cckgqr.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cckgsv.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/ccklse.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cdrges.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cdrgev.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cdrgsx.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cdrgvx.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cdrvbd.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cdrves.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cdrvev.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cdrvgg.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cdrvsg.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cdrvst.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cdrvsx.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cdrvvx.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cerrbd.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cerrec.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cerred.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cerrgg.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cerrhs.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cerrst.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cget02.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cget10.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cget22.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cget23.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cget24.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cget35.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cget36.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cget37.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cget38.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cget51.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cget52.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cget54.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cglmts.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cgqrts.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cgrqts.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cgsvts.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/chbt21.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/chet21.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/chet22.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/chkxer.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/chpt21.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/chst01.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/clarfy.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/clarhs.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/clatm4.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/clctes.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/clctsx.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/clsets.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/csbmv.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/csgt01.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cslect.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cstt21.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cstt22.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cunt01.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cunt03.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dbdt01.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dbdt02.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dbdt03.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dchkbb.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dchkbd.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dchkbk.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dchkbl.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dchkec.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dchkee.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dchkgg.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dchkgk.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dchkgl.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dchkhs.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dchksb.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dchkst.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dckglm.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dckgqr.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dckgsv.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dcklse.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/ddrges.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/ddrgev.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/ddrgsx.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/ddrgvx.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/ddrvbd.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/ddrves.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/ddrvev.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/ddrvgg.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/ddrvsg.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/ddrvst.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/ddrvsx.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/ddrvvx.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/derrbd.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/derrec.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/derred.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/derrgg.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/derrhs.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/derrst.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dget02.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dget10.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dget22.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dget23.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dget24.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dget31.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dget32.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dget33.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dget34.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dget35.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dget36.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dget37.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dget38.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dget39.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dget51.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dget52.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dget53.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dget54.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dglmts.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dgqrts.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dgrqts.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dgsvts.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dhst01.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dlafts.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dlahd2.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dlarfy.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dlarhs.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dlasum.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dlatb9.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dlatm4.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dlctes.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dlctsx.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dlsets.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dort01.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dort03.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dsbt21.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dsgt01.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dslect.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dspt21.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dstech.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dstect.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dstt21.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dstt22.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dsvdch.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dsvdct.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dsxt1.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dsyt21.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dsyt22.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/ilaenv.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sbdt01.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sbdt02.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sbdt03.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/schkbb.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/schkbd.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/schkbk.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/schkbl.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/schkec.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/schkee.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/schkgg.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/schkgk.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/schkgl.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/schkhs.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/schksb.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/schkst.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sckglm.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sckgqr.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sckgsv.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/scklse.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sdrges.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sdrgev.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sdrgsx.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sdrgvx.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sdrvbd.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sdrves.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sdrvev.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sdrvgg.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sdrvsg.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sdrvst.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sdrvsx.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sdrvvx.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/serrbd.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/serrec.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/serred.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/serrgg.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/serrhs.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/serrst.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sget02.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sget10.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sget22.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sget23.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sget24.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sget31.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sget32.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sget33.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sget34.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sget35.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sget36.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sget37.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sget38.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sget39.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sget51.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sget52.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sget53.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sget54.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sglmts.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sgqrts.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sgrqts.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sgsvts.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/shst01.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/slafts.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/slahd2.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/slarfy.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/slarhs.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/slasum.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/slatb9.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/slatm4.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/slctes.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/slctsx.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/slsets.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sort01.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sort03.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/ssbt21.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/ssgt01.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sslect.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sspt21.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sstech.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sstect.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sstt21.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sstt22.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/ssvdch.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/ssvdct.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/ssxt1.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/ssyt21.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/ssyt22.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/xerbla.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/xlaenv.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zbdt01.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zbdt02.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zbdt03.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zchkbb.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zchkbd.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zchkbk.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zchkbl.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zchkec.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zchkee.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zchkgg.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zchkgk.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zchkgl.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zchkhb.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zchkhs.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zchkst.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zckglm.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zckgqr.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zckgsv.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zcklse.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zdrges.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zdrgev.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zdrgsx.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zdrgvx.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zdrvbd.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zdrves.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zdrvev.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zdrvgg.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zdrvsg.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zdrvst.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zdrvsx.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zdrvvx.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zerrbd.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zerrec.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zerred.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zerrgg.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zerrhs.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zerrst.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zget02.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zget10.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zget22.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zget23.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zget24.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zget35.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zget36.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zget37.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zget38.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zget51.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zget52.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zget54.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zglmts.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zgqrts.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zgrqts.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zgsvts.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zhbt21.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zhet21.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zhet22.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zhpt21.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zhst01.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zlarfy.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zlarhs.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zlatm4.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zlctes.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zlctsx.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zlsets.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zsbmv.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zsgt01.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zslect.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zstt21.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zstt22.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zunt01.o \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zunt03.o 

C_DEPS += \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/alahdg.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/alareq.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/alarqg.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/alasmg.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/alasum.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/alasvm.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cbdt01.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cbdt02.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cbdt03.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cchkbb.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cchkbd.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cchkbk.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cchkbl.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cchkec.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cchkee.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cchkgg.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cchkgk.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cchkgl.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cchkhb.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cchkhs.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cchkst.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cckglm.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cckgqr.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cckgsv.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/ccklse.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cdrges.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cdrgev.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cdrgsx.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cdrgvx.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cdrvbd.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cdrves.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cdrvev.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cdrvgg.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cdrvsg.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cdrvst.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cdrvsx.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cdrvvx.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cerrbd.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cerrec.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cerred.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cerrgg.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cerrhs.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cerrst.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cget02.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cget10.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cget22.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cget23.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cget24.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cget35.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cget36.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cget37.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cget38.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cget51.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cget52.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cget54.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cglmts.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cgqrts.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cgrqts.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cgsvts.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/chbt21.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/chet21.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/chet22.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/chkxer.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/chpt21.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/chst01.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/clarfy.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/clarhs.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/clatm4.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/clctes.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/clctsx.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/clsets.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/csbmv.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/csgt01.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cslect.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cstt21.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cstt22.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cunt01.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/cunt03.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dbdt01.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dbdt02.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dbdt03.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dchkbb.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dchkbd.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dchkbk.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dchkbl.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dchkec.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dchkee.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dchkgg.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dchkgk.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dchkgl.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dchkhs.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dchksb.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dchkst.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dckglm.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dckgqr.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dckgsv.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dcklse.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/ddrges.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/ddrgev.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/ddrgsx.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/ddrgvx.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/ddrvbd.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/ddrves.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/ddrvev.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/ddrvgg.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/ddrvsg.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/ddrvst.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/ddrvsx.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/ddrvvx.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/derrbd.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/derrec.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/derred.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/derrgg.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/derrhs.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/derrst.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dget02.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dget10.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dget22.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dget23.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dget24.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dget31.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dget32.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dget33.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dget34.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dget35.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dget36.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dget37.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dget38.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dget39.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dget51.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dget52.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dget53.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dget54.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dglmts.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dgqrts.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dgrqts.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dgsvts.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dhst01.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dlafts.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dlahd2.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dlarfy.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dlarhs.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dlasum.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dlatb9.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dlatm4.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dlctes.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dlctsx.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dlsets.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dort01.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dort03.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dsbt21.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dsgt01.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dslect.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dspt21.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dstech.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dstect.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dstt21.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dstt22.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dsvdch.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dsvdct.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dsxt1.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dsyt21.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/dsyt22.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/ilaenv.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sbdt01.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sbdt02.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sbdt03.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/schkbb.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/schkbd.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/schkbk.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/schkbl.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/schkec.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/schkee.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/schkgg.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/schkgk.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/schkgl.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/schkhs.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/schksb.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/schkst.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sckglm.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sckgqr.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sckgsv.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/scklse.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sdrges.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sdrgev.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sdrgsx.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sdrgvx.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sdrvbd.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sdrves.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sdrvev.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sdrvgg.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sdrvsg.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sdrvst.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sdrvsx.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sdrvvx.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/serrbd.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/serrec.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/serred.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/serrgg.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/serrhs.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/serrst.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sget02.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sget10.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sget22.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sget23.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sget24.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sget31.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sget32.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sget33.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sget34.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sget35.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sget36.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sget37.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sget38.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sget39.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sget51.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sget52.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sget53.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sget54.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sglmts.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sgqrts.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sgrqts.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sgsvts.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/shst01.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/slafts.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/slahd2.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/slarfy.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/slarhs.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/slasum.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/slatb9.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/slatm4.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/slctes.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/slctsx.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/slsets.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sort01.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sort03.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/ssbt21.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/ssgt01.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sslect.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sspt21.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sstech.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sstect.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sstt21.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/sstt22.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/ssvdch.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/ssvdct.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/ssxt1.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/ssyt21.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/ssyt22.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/xerbla.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/xlaenv.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zbdt01.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zbdt02.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zbdt03.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zchkbb.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zchkbd.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zchkbk.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zchkbl.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zchkec.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zchkee.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zchkgg.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zchkgk.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zchkgl.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zchkhb.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zchkhs.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zchkst.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zckglm.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zckgqr.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zckgsv.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zcklse.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zdrges.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zdrgev.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zdrgsx.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zdrgvx.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zdrvbd.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zdrves.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zdrvev.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zdrvgg.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zdrvsg.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zdrvst.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zdrvsx.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zdrvvx.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zerrbd.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zerrec.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zerred.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zerrgg.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zerrhs.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zerrst.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zget02.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zget10.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zget22.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zget23.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zget24.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zget35.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zget36.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zget37.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zget38.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zget51.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zget52.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zget54.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zglmts.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zgqrts.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zgrqts.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zgsvts.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zhbt21.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zhet21.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zhet22.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zhpt21.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zhst01.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zlarfy.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zlarhs.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zlatm4.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zlctes.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zlctsx.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zlsets.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zsbmv.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zsgt01.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zslect.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zstt21.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zstt22.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zunt01.d \
./ndk-modules/lapack/jni/clapack/TESTING/EIG/zunt03.d 


# Each subdirectory must supply rules for building sources it contributes
ndk-modules/lapack/jni/clapack/TESTING/EIG/%.o: ../ndk-modules/lapack/jni/clapack/TESTING/EIG/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -O2 -g -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


